export const theme = {
  colors: {
    primary: '#6C63FF',
    primaryDark: '#5952D4',
    primaryLight: '#8B7DFF',
    secondary: '#FF6B6B',
    secondaryDark: '#E74C3C',
    secondaryLight: '#FF8A8A',
    success: '#4ECDC4',
    successDark: '#26D0CE',
    warning: '#FFE66D',
    warningDark: '#FFC107',
    error: '#FF6B6B',
    errorDark: '#E74C3C',
    background: '#F8F9FE',
    surface: '#FFFFFF',
    card: '#FFFFFF',
    text: '#2C3E50',
    textSecondary: '#7F8C8D',
    textLight: '#BDC3C7',
    border: '#E8ECEF',
    borderLight: '#F4F6F9',
    overlay: 'rgba(0, 0, 0, 0.4)',
    gradient: {
      primary: ['#6C63FF', '#5952D4'],
      secondary: ['#FF6B6B', '#E74C3C'],
      success: ['#4ECDC4', '#26D0CE'],
      background: ['#F8F9FE', '#FFFFFF'],
      card: ['#FFFFFF', '#F8F9FE'],
    }
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    round: 50,
  },
  fontSize: {
    xs: 12,
    sm: 14,
    md: 16,
    lg: 18,
    xl: 24,
    xxl: 32,
    xxxl: 48,
  },
  fontWeight: {
    regular: '400',
    medium: '500',
    semibold: '600',
    bold: '700',
  },
  animations: {
    fast: 200,
    medium: 300,
    slow: 500,
  },
};

export type Theme = typeof theme;
